name: crypto_pro
description: "Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  talker_dio_logger: ^2.4.0
  talker_bloc_logger: ^2.4.0
  firebase_core: ^2.24.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  talker_flutter: ^3.6.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
